export const CLR='#f97316';

export const CDS=[
  {id:'cd1', n:1, icon:'👑', label:'Epic Meaning & Calling',
   side:'white', brain:'right', color:'#a78bfa',
   pos:{angle:-90},
   desc:'O jogador acredita que está fazendo algo maior que si mesmo ou que foi "escolhido" para uma missão especial. Projetos open-source, "Beginner\'s Luck" e a sensação de ser o herói de uma história épica.',
   mechanics:['Narrativa de destino / escolhido','Lore exclusivo para veteranos','Missão de fundação do servidor','Easter eggs e segredos profundos'],
   questions:['Que missão maior o jogo oferece além de ganhar?','O jogador sente que sua participação importa para algo além de si mesmo?','Como o jogo cria a sensação de que ele foi escolhido ou tem um talento especial?']},
  {id:'cd2', n:2, icon:'⭐', label:'Development & Accomplishment',
   side:'white', brain:'left', color:'#fbbf24',
   pos:{angle:-45},
   desc:'A drive interna de progredir, desenvolver habilidades e superar desafios. Badges e troféus só são significativos se houver um desafio real por trás. É a CD mais fácil de designar — e onde a maioria dos PBLs (pontos, badges, leaderboards) opera.',
   mechanics:['Pontos de experiência e levels','Árvore de habilidades','Conquistas e troféus','Leaderboards e rankings'],
   questions:['Como o jogo mostra ao jogador que ele está ficando melhor?','Quais são os marcos visíveis de progressão?','Os desafios escalam de forma que a conquista continue significativa?']},
  {id:'cd3', n:3, icon:'🎨', label:'Empowerment of Creativity & Feedback',
   side:'white', brain:'right', color:'#34d399',
   pos:{angle:0},
   desc:'Usuários engajados num processo criativo onde precisam descobrir combinações e ver os resultados de suas decisões. Legos e pintura são divertidos por si só — criam "Evergreen Mechanics" onde o designer não precisa adicionar conteúdo constantemente.',
   mechanics:['Construção livre / sandbox','Personalização de personagem/base','Resolução de puzzles com múltiplas soluções','Combinação de itens e crafting'],
   questions:['Onde o jogador pode expressar criatividade dentro do sistema?','O jogo oferece feedback imediato e significativo sobre as escolhas criativas?','Há profundidade suficiente para manter a exploração criativa interessante por horas?']},
  {id:'cd4', n:4, icon:'💰', label:'Ownership & Possession',
   side:'neutral', brain:'left', color:'#fb923c',
   pos:{angle:45},
   desc:'Jogadores motivados porque sentem que possuem algo. Quem sente ownership quer melhorar o que tem e possuir mais. Abrange bens virtuais, moedas in-game, customização de avatar e o prazer de colecionar.',
   mechanics:['Inventário e coleção de itens','Moeda e economia virtual','Personalização de avatar/base','Sistema de crafting e recursos'],
   questions:['O que o jogador pode "possuir" dentro do jogo?','Como o jogo faz o jogador sentir que seus itens e personagens são realmente seus?','Há sistemas de customização que aumentam o senso de identidade e posse?']},
  {id:'cd5', n:5, icon:'👥', label:'Social Influence & Relatedness',
   side:'white', brain:'right', color:'#22d3ee',
   pos:{angle:-135},
   desc:'Todos os elementos sociais: mentoria, aceitação, respostas sociais, companheirismo, competição e inveja. Quando você vê um amigo incrível numa habilidade, você é motivado a alcançar o mesmo nível. Inclui também a nostalgia e conexão com pessoas/lugares.',
   mechanics:['Guilds e partidos','Mecânicas de PvP e competição','Sistemas de mentor/pupilo','Presentes e comércio entre jogadores'],
   questions:['Como jogadores se conectam, comparam e influenciam uns aos outros?','Há mecanismos de cooperação e/ou competição entre jogadores?','O jogo cria momentos de performance social ou status visível?']},
  {id:'cd6', n:6, icon:'💎', label:'Scarcity & Impatience',
   side:'black', brain:'left', color:'#ef4444',
   pos:{angle:180},
   desc:'A drive de querer algo que não se pode ter — ainda. Itens limitados, acesso exclusivo, sistemas de agendamento (volte em 2 horas). O Facebook usou isso quando era só para universitários. Cria desejo precisamente por ser inacessível.',
   mechanics:['Itens de edição limitada','Energia/stamina com recarga temporal','Filas de espera ou acesso exclusivo','Ofertas por tempo limitado'],
   questions:['O que no jogo é escasso por design (não pode ser comprado a qualquer momento)?','Como a impaciência é usada para criar antecipação e desejo?','O scarcity é calibrado para ser excitante sem ser frustrante?']},
  {id:'cd7', n:7, icon:'🎲', label:'Unpredictability & Curiosity',
   side:'black', brain:'right', color:'#8b5cf6',
   pos:{angle:135},
   desc:'A drive de não saber o que vai acontecer. Jogos de azar usam isso, mas também qualquer sistema de loot, recompensas variáveis e mistérios. Responsável pelo efeito de "mais um episódio" ou continuar jogando para ver o que vem.',
   mechanics:['Loot aleatório e caixas de recompensa','Eventos randômicos e encontros inesperados','Narrativa com revelações surpresa','Sistemas procedurais e geração aleatória'],
   questions:['Onde o jogo usa variabilidade intencional para criar antecipação?','Como o mistério e a curiosidade são mantidos ao longo da experiência?','O jogo calibra a imprevisibilidade para evitar frustração excessiva?']},
  {id:'cd8', n:8, icon:'💀', label:'Loss & Avoidance',
   side:'black', brain:'left', color:'var(--gdd-dim)',
   pos:{angle:90},
   desc:'A motivação de evitar algo negativo. O medo de perder progresso, itens, status ou oportunidades que não voltarão. Sistemas de "streak" dependem disso. É a CD mais poderosa a curto prazo, mas o mais ético é usá-la com moderação.',
   mechanics:['Permadeath ou perda de progresso','Missões e eventos com prazo (expiram)','Sistema de streak com punição por quebra','Limitação de tentativas / Game Over'],
   questions:['O que o jogador pode perder e não quer perder?','Como a ameaça de perda cria urgência e engajamento?','O uso de Loss & Avoidance está calibrado para motivar sem criar ansiedade negativa?']},
];

export const STEPS=[
  {id:'white',   label:'White Hat',   icon:'☀️'},
  {id:'black',   label:'Black Hat',   icon:'🌑'},
  {id:'balance', label:'Balanço',     icon:'⚖️'},
  {id:'compile', label:'Compilar',    icon:'📄'},
];

export const GUIDE=[
  {title:'White Hat — drives positivas e empoderadoras',
   body:'As 4 drives do topo do octágono são "White Hat": motivam de forma positiva, criando sentimentos de poder, significado e satisfação. Jogadores motivados por White Hat se sentem bem consigo mesmos.\n\nCD1 é a mais poderosa a longo prazo: senso de missão e legado. CD2 é a mais fácil de implementar: pontos e progressão. CD3 cria engajamento "evergreen" através de criatividade. CD5 usa o poder do social.\n\nProblema de depender só do White Hat: pode não criar urgência suficiente para a ação imediata.'},
  {title:'Black Hat — drives de urgência e tensão',
   body:'As 3 drives do fundo do octágono são "Black Hat": motivam por pressão, medo e desejo de algo inacessível. Criam engajamento poderoso a curto prazo, mas podem deixar o jogador se sentindo mal se usadas em excesso.\n\nCD6 cria desejo pelo que não pode ser obtido facilmente. CD7 mantém o jogador voltando para descobrir o que há depois. CD8 usa o medo da perda para criar urgência.\n\nCD4 (Ownership) é considerada neutra — não é claramente White ou Black Hat.\n\nO equilíbrio ideal: White Hat para retenção a longo prazo, Black Hat para engajamento imediato.'},
  {title:'Balanço: Left Brain vs Right Brain',
   body:'Além do eixo White/Black Hat, Chou divide o octágono em Left Brain (drives extrínsecas, analíticas) e Right Brain (drives intrínsecas, criativas).\n\nLeft Brain (CD2, CD4, CD6, CD8): motivado por objetivos concretos, recompensas tangíveis e progressão lógica. Jogadores Left Brain param quando atingem o objetivo.\n\nRight Brain (CD1, CD3, CD5, CD7): motivado por curiosidade, criatividade e conexão. Jogadores Right Brain podem jogar indefinidamente — o jogo em si é a recompensa.\n\nO Octalysis Score mede a intensidade de cada CD de 0 a 10. Um jogo equilibrado deve ter score distribuído em múltiplas drives, sem dependência excessiva de uma única CD.'},
];
