-- Historical Supabase schema draft placeholder.
--
-- The original version of this migration contained planned normalized tables
-- such as profiles, documents, document_messages, production_tasks,
-- canvas_boards, assets, and user_settings. Those tables are not used by the
-- current runtime and must not be created by active migrations until their
-- repositories, ownership model, RLS policies, and product requirements exist.
--
-- Current active runtime schema is intentionally limited to:
-- - public.projects
-- - public.project_data
--
-- The active tables are created and secured by later migrations:
-- - 20260708000000_secure_projects_rls.sql
-- - 20260708001000_project_data_blob_rls.sql
--
-- Future normalized schema planning remains in docs/architecture.
